# MQTT Broker Configuration
mqtt_server: 192.168.00.00
mqtt_port: 1883
mqtt_username: username
mqtt_password: password

# MQTT Topics
source_topic: moode/audio/source
details_topic: moode/audio/details
command_topic: moode/audio/command

# Additional configuration
debug: false
max_lines_librespot: 100
max_lines_airplay: 30
logfile_max_age_seconds: 5
